import { PublicMenuResponse } from "@/types/api";

export const MOCK_MENU: PublicMenuResponse = {
  restaurantId: "1",
  restaurantName: "La Terraza de María",
  restaurantLogo: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=100&h=100&fit=crop&crop=faces",
  currency: "€",
  categories: [
    {
      id: "cat-1",
      name: "Entrantes",
      description: "Para empezar con buen pie",
      imageUrl: "",
      displayOrder: 1,
      products: [
        {
          id: "p-1",
          categoryId: "cat-1",
          name: "Croquetas caseras de jamón",
          description: "8 unidades de croquetas cremosas de jamón ibérico, crujientes por fuera y suaves por dentro.",
          price: 9.50,
          discountPrice: null,
          vatRate: 10,
          sku: "ENT-001",
          imageUrl: "https://images.unsplash.com/photo-1554866585-cd94860890b7?w=400&h=400&fit=crop",
          allergens: [
            { id: "a-1", code: "GLUTEN", name: "Gluten", description: "Contiene gluten", iconUrl: "", active: true },
            { id: "a-2", code: "LACTOSE", name: "Lactosa", description: "Contiene lactosa", iconUrl: "", active: true },
          ],
          tags: ["Popular", "Casero"],
          calories: 320,
          preparationTime: 12,
          available: true,
          displayOrder: 1,
          createdAt: "2024-01-01T00:00:00Z",
        },
        {
          id: "p-2",
          categoryId: "cat-1",
          name: "Ensalada César",
          description: "Lechuga romana, pollo a la plancha, parmesano, picatostes y salsa César.",
          price: 11.00,
          discountPrice: 8.90,
          vatRate: 10,
          sku: "ENT-002",
          imageUrl: "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=400&h=400&fit=crop",
          allergens: [
            { id: "a-1", code: "GLUTEN", name: "Gluten", description: "", iconUrl: "", active: true },
            { id: "a-3", code: "EGG", name: "Huevo", description: "", iconUrl: "", active: true },
          ],
          tags: ["Saludable"],
          calories: 280,
          preparationTime: 8,
          available: true,
          displayOrder: 2,
          createdAt: "2024-01-01T00:00:00Z",
        },
        {
          id: "p-3",
          categoryId: "cat-1",
          name: "Patatas bravas",
          description: "Patatas fritas con doble salsa: brava picante y alioli casero.",
          price: 7.50,
          discountPrice: null,
          vatRate: 10,
          sku: "ENT-003",
          imageUrl: "https://images.unsplash.com/photo-1585672840563-f2af2ced55c9?w=400&h=400&fit=crop",
          allergens: [
            { id: "a-3", code: "EGG", name: "Huevo", description: "", iconUrl: "", active: true },
          ],
          tags: ["Clásico"],
          calories: 410,
          preparationTime: 10,
          available: true,
          displayOrder: 3,
          createdAt: "2024-01-01T00:00:00Z",
        },
      ],
    },
    {
      id: "cat-2",
      name: "Principales",
      description: "Nuestros platos estrella",
      imageUrl: "",
      displayOrder: 2,
      products: [
        {
          id: "p-4",
          categoryId: "cat-2",
          name: "Risotto de setas y trufa",
          description: "Arroz carnaroli cremoso con mezcla de setas de temporada y aceite de trufa negra.",
          price: 16.50,
          discountPrice: null,
          vatRate: 10,
          sku: "PRI-001",
          imageUrl: "https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=400&h=400&fit=crop",
          allergens: [
            { id: "a-2", code: "LACTOSE", name: "Lactosa", description: "", iconUrl: "", active: true },
          ],
          tags: ["Chef recomienda"],
          calories: 520,
          preparationTime: 20,
          available: true,
          displayOrder: 1,
          createdAt: "2024-01-01T00:00:00Z",
        },
        {
          id: "p-5",
          categoryId: "cat-2",
          name: "Solomillo de ternera",
          description: "200g de solomillo a la parrilla con reducción de Pedro Ximénez y guarnición de verduras.",
          price: 22.90,
          discountPrice: null,
          vatRate: 10,
          sku: "PRI-002",
          imageUrl: "https://images.unsplash.com/photo-1546964124-0cce460f38ef?w=400&h=400&fit=crop",
          allergens: [],
          tags: ["Premium"],
          calories: 650,
          preparationTime: 25,
          available: true,
          displayOrder: 2,
          createdAt: "2024-01-01T00:00:00Z",
        },
        {
          id: "p-6",
          categoryId: "cat-2",
          name: "Lubina a la espalda",
          description: "Lubina fresca abierta a la plancha con ajo, guindilla y aceite de oliva virgen extra.",
          price: 18.90,
          discountPrice: 15.90,
          vatRate: 10,
          sku: "PRI-003",
          imageUrl: "https://images.unsplash.com/photo-1534604973900-c43ab4c2e0ab?w=400&h=400&fit=crop",
          allergens: [
            { id: "a-4", code: "FISH", name: "Pescado", description: "", iconUrl: "", active: true },
          ],
          tags: ["Oferta", "Fresco"],
          calories: 380,
          preparationTime: 18,
          available: true,
          displayOrder: 3,
          createdAt: "2024-01-01T00:00:00Z",
        },
        {
          id: "p-7",
          categoryId: "cat-2",
          name: "Hamburguesa gourmet",
          description: "Carne madurada 180g, queso cheddar, bacon crujiente, cebolla caramelizada y salsa de la casa.",
          price: 14.50,
          discountPrice: null,
          vatRate: 10,
          sku: "PRI-004",
          imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=400&fit=crop",
          allergens: [
            { id: "a-1", code: "GLUTEN", name: "Gluten", description: "", iconUrl: "", active: true },
            { id: "a-2", code: "LACTOSE", name: "Lactosa", description: "", iconUrl: "", active: true },
            { id: "a-3", code: "EGG", name: "Huevo", description: "", iconUrl: "", active: true },
          ],
          tags: ["Popular"],
          calories: 780,
          preparationTime: 15,
          available: true,
          displayOrder: 4,
          createdAt: "2024-01-01T00:00:00Z",
        },
      ],
    },
    {
      id: "cat-3",
      name: "Postres",
      description: "El broche final perfecto",
      imageUrl: "",
      displayOrder: 3,
      products: [
        {
          id: "p-8",
          categoryId: "cat-3",
          name: "Tarta de queso vasca",
          description: "Tarta de queso al horno estilo San Sebastián, cremosa por dentro con exterior caramelizado.",
          price: 7.50,
          discountPrice: null,
          vatRate: 10,
          sku: "POS-001",
          imageUrl: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=400&h=400&fit=crop",
          allergens: [
            { id: "a-2", code: "LACTOSE", name: "Lactosa", description: "", iconUrl: "", active: true },
            { id: "a-3", code: "EGG", name: "Huevo", description: "", iconUrl: "", active: true },
          ],
          tags: ["Favorito"],
          calories: 420,
          preparationTime: 5,
          available: true,
          displayOrder: 1,
          createdAt: "2024-01-01T00:00:00Z",
        },
        {
          id: "p-9",
          categoryId: "cat-3",
          name: "Tiramisú",
          description: "Capas de bizcocho de café, mascarpone y cacao en polvo.",
          price: 6.90,
          discountPrice: null,
          vatRate: 10,
          sku: "POS-002",
          imageUrl: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400&h=400&fit=crop",
          allergens: [
            { id: "a-2", code: "LACTOSE", name: "Lactosa", description: "", iconUrl: "", active: true },
            { id: "a-3", code: "EGG", name: "Huevo", description: "", iconUrl: "", active: true },
            { id: "a-1", code: "GLUTEN", name: "Gluten", description: "", iconUrl: "", active: true },
          ],
          tags: [],
          calories: 350,
          preparationTime: 5,
          available: true,
          displayOrder: 2,
          createdAt: "2024-01-01T00:00:00Z",
        },
      ],
    },
    {
      id: "cat-4",
      name: "Bebidas",
      description: "",
      imageUrl: "",
      displayOrder: 4,
      products: [
        {
          id: "p-10",
          categoryId: "cat-4",
          name: "Agua mineral 50cl",
          description: "",
          price: 2.50,
          discountPrice: null,
          vatRate: 10,
          sku: "BEB-001",
          imageUrl: "https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=400&h=400&fit=crop",
          allergens: [],
          tags: [],
          calories: 0,
          preparationTime: 1,
          available: true,
          displayOrder: 1,
          createdAt: "2024-01-01T00:00:00Z",
        },
        {
          id: "p-11",
          categoryId: "cat-4",
          name: "Copa de vino tinto Rioja",
          description: "Crianza D.O.Ca. Rioja, 12 meses en barrica de roble.",
          price: 4.50,
          discountPrice: null,
          vatRate: 10,
          sku: "BEB-002",
          imageUrl: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=400&fit=crop",
          allergens: [
            { id: "a-5", code: "SULPHITES", name: "Sulfitos", description: "", iconUrl: "", active: true },
          ],
          tags: [],
          calories: 85,
          preparationTime: 1,
          available: true,
          displayOrder: 2,
          createdAt: "2024-01-01T00:00:00Z",
        },
        {
          id: "p-12",
          categoryId: "cat-4",
          name: "Cerveza artesana IPA",
          description: "India Pale Ale de elaboración local, notas cítricas y amargor equilibrado. 33cl.",
          price: 4.00,
          discountPrice: 3.50,
          vatRate: 10,
          sku: "BEB-003",
          imageUrl: "https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=400&h=400&fit=crop",
          allergens: [
            { id: "a-1", code: "GLUTEN", name: "Gluten", description: "", iconUrl: "", active: true },
          ],
          tags: ["Artesana"],
          calories: 150,
          preparationTime: 1,
          available: true,
          displayOrder: 3,
          createdAt: "2024-01-01T00:00:00Z",
        },
        {
          id: "p-13",
          categoryId: "cat-4",
          name: "Refresco",
          description: "Coca-Cola, Fanta, Sprite o Aquarius.",
          price: 2.90,
          discountPrice: null,
          vatRate: 10,
          sku: "BEB-004",
          imageUrl: "https://images.unsplash.com/photo-1581006852262-e4307cf6283a?w=400&h=400&fit=crop",
          allergens: [],
          tags: [],
          calories: 140,
          preparationTime: 1,
          available: true,
          displayOrder: 4,
          createdAt: "2024-01-01T00:00:00Z",
        },
      ],
    },
  ],
};
